[bind]
  address = "127.0.0.1"
  port = 8080

[dolibarr]
  main_url_root = "http://127.0.0.1:8080"
  main_data_root = "/hab/svc/dolibarr/data/documents"

  [dolibarr.db]
  host = "localhost"
  port = 3306
  name = "dolibarr"
  user = "dolibarr"
  password = "dolibarr"