#!/bin/sh

exec 2>&1

## Create needed directories
mkdir -p {{pkg.svc_var_path}}/spool

## Adjust rights and permissions
# Config path
chmod 755 {{pkg.svc_config_path}}
chmod 644 {{pkg.svc_config_path}}/*
# Data path
chown -R postfix:postfix {{pkg.svc_data_path}}
chmod -R 700 {{pkg.svc_data_path}}
# postdrop executables
chgrp postdrop {{pkg.path}}/sbin/postqueue
chgrp postdrop {{pkg.path}}/sbin/postdrop
chmod g+s {{pkg.path}}/sbin/postqueue
chmod g+s {{pkg.path}}/sbin/postdrop