#!/bin/sh

exec 2>&1

mkdir -p {{pkg.svc_var_path}}/config
mkdir -p {{pkg.svc_var_path}}/downloads
cp -r {{pkg.svc_config_path}}/* {{pkg.svc_var_path}}/config/
touch {{pkg.svc_var_path}}/deluge.log

chown hab:hab {{pkg.svc_var_path}}
