[bind]
  address = "127.0.0.1"
  port = 8080

[auth]
  enabled = false
  name = "Restricted Area"
  credentials = [
    # output of htpasswd -nb admin admin
    "admin:$apr1$Hf868va7$O.K0bMvda/3.pyjd1ZL3Z/"
  ]

[kanboard]
  plugin_installer = false
  storage_directory = "/tmp/kanboard"

  [kanboard.db]
  driver = "mysql"
  hostname = "localhost"
  port = 3306
  username = "kanboard"
  password = ""
  name = "kanboard"

  [kanboard.mail]
  from = "replace-me@kanboard.local"

    [kanboard.mail.smtp]
    enabled = false
    hostname = ""
    port = 25
    username = ""
    password = ""

