[agendav]
plan_path = "agendav"

[ampache]
plan_path = "ampache"

[baikal]
plan_path = "baikal"

[boinc-client]
plan_path = "boinc-client"

[boost]
plan_path = "boost"

[boost-build]
plan_path = "boost-build"

[boost172]
plan_path = "boost172"

[certbot]
plan_path = "certbot"

[cronie]
plan_path = "cronie"

[deluge]
plan_path = "deluge"

[dovecot]
plan_path = "dovecot"

[h5ai]
plan_path = "h5ai"

[libmilter]
plan_path = "libmilter"

[libowfat]
plan_path = "libowfat"

[libtorrent]
plan_path = "libtorrent"

[mkdocs]
plan_path = "mkdocs"

[mysql-client]
plan_path = "mysql-client"

[mytinytodo]
plan_path = "mytinytodo"

[opendkim]
plan_path = "opendkim"

[opentracker]
plan_path = "opentracker"

[php-fpm]
plan_path = "php-fpm"

[phpmyadmin]
plan_path = "phpmyadmin"

[postfix]
plan_path = "postfix"

[postfixadmin]
plan_path = "postfixadmin"

[rainloop]
plan_path = "rainloop"

[rclone]
plan_path = "rclone"

[resilio-sync]
plan_path = "resilio-sync"

[reverse-proxy]
plan_path = "reverse-proxy"

[thttpd]
plan_path = "thttpd"

[umurmur]
plan_path = "umurmur"

[wiki-js]
plan_path = "wiki-js"

[zlib-static]
plan_path = "zlib-static"
