# We didn't choose to use the default dovecot configuration files
# structure, since it conveys much more than what this package can
# actually offer. Instead, we've grouped configurations by categories
# using Dovecot ones whenever it made sense to.

dovecot_config_version = {{pkg.version}}
dovecot_storage_version = {{pkg.version}}

##
## ssl configuration
##

ssl = required

ssl_server_cert_file = {{cfg.ssl.certificate_path}}
ssl_server_key_file = {{cfg.ssl.certificate_key_path}}
ssl_server_dh_file = {{pkg.svc_var_path}}/dh.pem

ssl_min_protocol = {{cfg.ssl.min_protocol}}
ssl_cipher_list = {{ strJoin cfg.ssl.ciphers ":" }}
ssl_server_prefer_ciphers = server

##
## sql configuration
##

sql_driver = mysql

mysql dovecot {
  host = {{cfg.mysql.host}}
  port = {{cfg.mysql.port}}
  user = {{cfg.mysql.username}}
  password = {{cfg.mysql.password}}
  dbname = {{cfg.mysql.dbname}}
}

##
## auth configuration
##

auth_mechanisms = {{ strJoin cfg.auth.auth_mechanisms " " }}
auth_allow_weak_schemes = {{cfg.auth.allow_weak_schemes}}

userdb static {
  fields {
    uid={{cfg.auth.user_db.uid}}
    gid={{cfg.auth.user_db.gid}}
    home={{cfg.auth.user_db.home}}
  }
}

passdb sql {
  default_password_scheme = {{cfg.auth.password_db.default_scheme}}
  query = {{cfg.auth.password_db.query}}
}

##
## mailboxes configuration
##

mail_driver = maildir
mail_path = {{cfg.mail.location}}
mailbox_list_layout = fs

namespace inbox {
  inbox = yes

  {{#each cfg.mail.mailboxes as |mailbox| ~}}
  mailbox {{mailbox.name}} {
    name = {{mailbox.name}}
    auto = {{mailbox.auto}}
    special_use = {{mailbox.special_use}}
  }
  {{/each ~}}
}

##
## protocol configuration
##

protocols = imap lmtp sieve

protocol imap {
  ## Nothing to add
}

protocol lmtp {
  postmaster_address = {{cfg.lmtp.postmaster_address}}
  hostname = {{cfg.lmtp.hostname}}
  mail_plugins {
    sieve = yes
  }
}

##
## service configuration
##

listen = *, ::

service auth {
  inet_listener postfix {
    listen = {{strJoin cfg.bind.sasl.addresses ", " }}
    port = {{cfg.bind.sasl.port}}
  }

  user = root
}

service imap-login {
  process_limit = 200

  inet_listener imap {
    listen = {{ strJoin cfg.bind.imap.addresses ", " }}
    port = 143
  }
}

service lmtp {
  process_min_avail = 5

  inet_listener lmtp {
    listen = {{strJoin cfg.bind.lmtp.addresses ", " }}
    port = 24
  }
}

service managesieve-login {
  inet_listener sieve {
    listen = {{strJoin cfg.bind.managesieve.addresses ", " }}
    port = 4190
  }
}