[ssl]
  certificate_path = ""
  certificate_key_path = ""
  ciphers = [
    "ALL",
    "!DH",
    "!kRSA",
    "!SRP",
    "!kDHd",
    "!DSS",
    "!aNULL",
    "!eNULL",
    "!EXPORT",
    "!DES",
    "!3DES",
    "!MD5",
    "!PSK",
    "!RC4",
    "!ADH",
    "!LOW@STRENGTH"
  ]
  min_protocol = "TLSv1.2"

[mysql]
  host = "127.0.0.1"
  port = 3306
  username = "dovecot"
  password = "dovecot"
  dbname = "dovecot"

[auth]
  auth_mechanisms = ["plain"]
  allow_weak_schemes = "yes"

  # Package supports only MySQL db
  [auth.password_db]
    query = ""
    # https://doc.dovecot.org/2.4.4/core/config/auth/schemes.html
    default_scheme = "MD5-CRYPT"
    
  # Package supports only static db
  [auth.user_db]
    uid = 500
    gid = 500
    home = "/home/vmail/%{user | domain}/%{user | username}"

[mail]
  # The package uses maildir only, and passes LAYOUT=fs
  location = "/home/vmail/%{user | domain}/%{user | username}/Maildir"

  [[mail.mailboxes]]
  name = "Drafts"
  auto = "subscribe"
  special_use = "\\Drafts"

  [[mail.mailboxes]]
  name = "Spam"
  auto = "subscribe"
  special_use = "\\Junk"

  [[mail.mailboxes]]
  name = "Trash"
  auto = "subscribe"
  special_use = "\\Trash"

  [[mail.mailboxes]]
  name = "Sent"
  auto = "subscribe"
  special_use = "\\Sent"

[lmtp]
  postmaster_address = "postmaster@example.com"
  hostname = "imap.example.com"

[bind]
  [bind.sasl]
    addresses = ["127.0.0.1", "::1"]
    port = 26
  [bind.imap]
    addresses = ["*", "::"]
  [bind.lmtp]
    addresses = ["127.0.0.1", "::1"]
    port = 24
  [bind.managesieve]
    addresses = ["127.0.0.1", "::1"]
