#!/bin/sh

exec 2>&1

if [ ! -f {{pkg.svc_var_path}}/dh.pem ]
then
    openssl dhparam -out {{pkg.svc_var_path}}/dh.pem 4096
fi

# User needed for authentication
if [ $(getent passwd dovenull) == "" ]
then
  useradd -M dovenull
fi
# User needed for dropping privileges
if [ $(getent passwd dovecot) == "" ]
then
  useradd -M dovecot
fi