#!/bin/sh

random_instance_number_file="{{pkg.svc_path}}/random_instance_number"

if [ ! -f $random_instance_number_file ]; then
    echo -n "$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 32 | head -n 1)" > $random_instance_number_file
fi