[bind]
  address = "127.0.0.1"
  port = 8080

[wordpress]
  debug = false
  contents_location = "/my/contents/directory"
  site_url = "https://mysite.tld"

  [wordpress.db]
  name = "wordpress"
  table_prefix = "wp_"
  user = "wordpress"
  password = "wordpress"
  host = "127.0.0.1"
