#!/bin/sh

exec 2>&1

# Nginx
mkdir -p {{pkg.svc_var_path}}/nginx

chown -R hab:hab {{pkg.svc_var_path}}
chown -R hab:hab {{pkg.svc_config_path}}

# mytinytodo
cp -R {{pkg.path}}/mytinytodo/* {{pkg.svc_data_path}}/

cp {{pkg.svc_config_path}}/mytinytodo.cfg.php {{pkg.svc_data_path}}/db/config.php

chown -R hab:hab {{pkg.svc_data_path}}
chmod -wx {{pkg.svc_data_path}}/db/config.php
