bind_address = "127.0.0.1"
bind_address_ipv6 = ""

[hsts]
  enabled = false
  max_age = 31536000

[ssl]
  protocols = [
    "TLSv1.2",
    "TLSv1.3"
  ]
  ciphers = [
    # OpenSSL 1.1.x ciphers aren't used at this moment,
    # If OpenSSL is updated, so will this package, and
    # we'll be ready.
    "ECDHE-ECDSA-CHACHA20-POLY1305", # OpenSSL 1.1.x
    "ECDHE-ECDSA-CHACHA20-POLY1305-D", # OpenSSL 1.1.x
    "ECDHE-RSA-CHACHA20-POLY1305", # OpenSSL 1.1.x
    "ECDHE-RSA-CHACHA20-POLY1305-D", # OpenSSL 1.1.x
    "ECDHE-ECDSA-AES256-GCM-SHA384", # OpenSSL 1.0.x
    "ECDHE-ECDSA-AES128-GCM-SHA256", # OpenSSL 1.0.x
    "ECDHE-RSA-AES256-GCM-SHA384", # OpenSSL 1.0.x
    "ECDHE-RSA-AES128-GCM-SHA256" # OpenSSL 1.0.x
  ]
  ecdh_curves = [
    "secp384r1"
  ]

[[servers]]
  domain_name = "example.org"
  certificate_path = "example.org.crt"
  certificate_key_path = "example.org.key"
  client_max_body_size = "2M"

  # [[servers.redirections]]
  #   code = 302
  #   source_path = "/to_redirect"
  #   destination_url = "https://example.org"

  [[servers.locations]]
    path = "/"
    address = "192.168.1.1"
    port = 8080
    remote_path = "" # appended to the remote URI
