#!/bin/bash

exec 2>&1

# Nginx
mkdir -p {{pkg.svc_var_path}}/nginx
chown hab:hab {{pkg.svc_var_path}}

# AgenDAV
cp -r {{pkg.path}}/agendav/* {{pkg.svc_data_path}}/
cp {{pkg.svc_config_path}}/agendav.settings.php {{pkg.svc_data_path}}/config/settings.php

chown -R hab:hab {{pkg.svc_data_path}}

pushd  {{pkg.svc_data_path}}
    bin/agendavcli migrations:migrate
popd
