#!/bin/sh

encryption_key_file="{{pkg.svc_path}}/encryption_key"

if [ ! -f $encryption_key_file ]; then
    echo -n "$(cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 32 | head -n 1)" > $encryption_key_file
fi