[bind]
  address = "127.0.0.1"
  port = 8080

[auth]
  enabled = false
  name = "Restricted Area"
  credentials = [
    # output of htpasswd -nb admin admin
    "admin:$apr1$Hf868va7$O.K0bMvda/3.pyjd1ZL3Z/"
  ]

[postfixadmin]
  # to fill in this value, use the following command
  # php -r "echo password_hash('some password here', PASSWORD_DEFAULT);"
  # defaults to "p4ssw0rd"
  setup_password = "$2y$10$iU5jY0NyL/ywdQ0khsZkD.j6e7gqW0jTF1ZWT78hjLbw51dlX.oYa"
  default_language = "en"
  homepage_url = "https://postfixadmin.domain.tld"

  [postfixadmin.database]
  # type can be one of:
  # mysql = MySQL 3.23 and 4.0, 4.1 or 5
  # mysqli = MySQL 4.1+ or MariaDB
  # pgsql = PostgreSQL
  # sqlite = SQLite 3
  type = "mysqli"
  host = "localhost"
  user = "postfix"
  password = "postfixadmin"
  name = "postfix"

  [postfixadmin.admin]
  email = ""
  name = "Postmaster"

  [postfixadmin.smtp]
  server = "localhost"
  port = "25"

  [postfixadmin.default_aliases]
  abuse = "abuse@change-this-to-your.domain.tld"
  hostmaster = "hostmaster@change-this-to-your.domain.tld"
  postmaster = "postmaster@change-this-to-your.domain.tld"
  webmaster = "webmaster@change-this-to-your.domain.tld"